spring:
  datasource:
    url: jdbc:mysql://docker-mysql:3306/my-web-algorithm?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: dockermysqlpassword
